# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "build/default/ckeditor"
    js_path:   "build/default/ckeditor/ckeditor.js"

    # Add Custom CSS Classes to Can Add With 'ckeditor_add_class' Plugin
    configs:
        my_config:
            magicline_everywhere: true
            stylesSet:
                - { name: "My Lightbox Style", element: "a", attributes: { class: "lightbox" }}
    styles:
        my_lightbox:
            - { name: "My Lightbox Style", element: "img", attributes: { class: "lightbox" }}
            
    toolbars:
        configs:
            example_toolbar: [ [ "Source" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]
            document_toolbar: [
                "@justify", "|", "@basicstyles", "@styles", "|", "@lists", "/", 
                "@links", "@media", "|", "@document"
            ]
            devpage_toolbar: [
                "@justify", "|", "@basicstyles", "@styles", "|", "@lists", "/", 
                "@links", "@media", "@dev_tools", "|", "@document"
            ]
            description_toolbar: ["@justify", "|", "@basicstyles", "@styles", "|", "@lists", "@links", "|", "@document"]
            
        items:
            basicstyles: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']
            styles: ['Styles','Format','Font','FontSize']
            justify: ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock']
            document: ['Source', 'Save', 'NewPage']
            lists: ['NumberedList', 'BulletedList']
            links: ['Link', 'Unlink', 'ckeditor_add_class']
            media: ['Image', 'lightbox']
            dev_tools: [ 'Simplebox', 'Simplebox-2', 'CodeSnippet', 'Indent', 'Outdent' ]
            
    plugins:
        codesnippet:
            path:     "/build/default/ckeditor/plugins/codesnippet/" # with trailing slash
            filename: "plugin.js"
        simplebox:
            path:     "/build/default/ckeditor/plugins/simplebox/" # with trailing slash
            filename: "plugin.js"
        lightbox:
            path:     "/build/default/ckeditor/plugins/lightbox/" # with trailing slash
            filename: "plugin.js"
        ckeditor_add_class:
            path:     "/build/default/ckeditor/plugins/ckeditor_add_class/" # with trailing slash
            filename: "plugin.js"

