twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        applicationIcon: '%applicationIcon%'
        applicationTitle: '%applicationTitle%'
        hasTopSearch: '%hasTopSearch%'
        formCreateAccount: '%vs_users.form_create_account%'
        webSiteUrl: "http://website.url"
        installedBundles: '%kernel.bundles%'
        pageCategoriesTaxonomyCode: '%vs_application.page_categories.taxonomy_code%'
        localesRepo: '@vs_application.repository.locale'
        applicationsRepo: '@vs_application.repository.application'
        
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

when@test:
    twig:
        strict_variables: true
