twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        siteIcon: 'build/images/sf-positive.svg'
        siteTitle: '%siteTitle%'
        lang: '%lang%'
        locale: '%locale%'
        webSiteUrl: "http://website.url"
        installedBundles: '%kernel.bundles%'
        pageCategoriesTaxonomyCode: '%vs_cms.page_categories.taxonomy_code%'
        
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

when@test:
    twig:
        strict_variables: true
