imports:
    - { resource: services/menu.yaml }

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    lang: 'en'
    locale: 'en_US'
    languages:
        en: English
        bg: Български
    applicationTitle: 'SuperAdmin Panel'
    menu.config_file: "%kernel.project_dir%/../config/packages/vs_application.yaml"
    
    vs_cms.page_categories.taxonomy_code: 'page-categories'
    
    vs_users.login_route: 'vs_application_login'
    vs_users.login_by: 'username'
    vs_users.api_token.lifetime: 3600
    vs_user.profile_pictures_dir: '%kernel.project_dir%/var/uploads/profile_pictures'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/AdminPanelKernel.php'
            - '../src/Tests/'
            
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        autowire: true
            
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

